Styling attempt 1
tedbjurlin/FaulknerCountyMuseumGallery pull request #27
Opened 2023-11-14 02:48 UTC by scottdaco

2023-11-14 03:59 UTC, tedbjurlin approved these changes

2023-11-14 03:59 UTC, tedbjurlin requested changes, later dismissed
It looks like there are some merge conflicts on this branch. We can merge it once you resolve those.

2023-11-15 20:16 UTC, scottdaco commented
fixed merge conflicts

2023-11-17 18:16 UTC, JCT03 approved these changes

2023-11-17 18:17 UTC, merged