more Styling
tedbjurlin/FaulknerCountyMuseumGallery pull request #40
Opened 2023-11-24 21:45 UTC by scottdaco

2023-11-25 19:41 UTC, tedbjurlin requested changes
I like where this is going, but I think we were talking about moving the admin login menu to the footer. In the identity branch, which has been merged into main, that change has already been made and the admin option in the header is only visible when an admin is logged in.

So I think you can just skip the admin buttons in the header

2023-11-26 20:43 UTC, scottdaco commented
did requested changes and resolved conflicts

2023-11-26 20:43 UTC, scottdaco commented
and more styling

2023-11-27 18:36 UTC, tedbjurlin approved these changes

2023-11-27 18:43 UTC, merged