centerred labels and addded button fade
tedbjurlin/FaulknerCountyMuseumGallery pull request #47
Opened 2023-11-27 21:25 UTC by scottdaco

2023-11-27 22:28 UTC, JCT03 requested changes
The footer is messed up on the about page. Looks good otherwise. Is there maybe a way to add a small space above the page labels?

2023-11-28 00:05 UTC, scottdaco commented
Fixed footer on about page. Will add space above page titles later

2023-11-28 22:18 UTC, scottdaco commented
addedd spacess

2023-11-29 18:12 UTC, JCT03 approved these changes

2023-11-29 18:12 UTC, merged